version: '3'

services:
  backend:
    image: node:18
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "5001:5001"
    command: >
      bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: >
      bash -c "npm install --legacy-peer-deps && npm run dev -- --host"
    depends_on:
      - backend
    restart: unless-stopped 